services:
  - type: web
    name: pdfmerger
    env: node
    buildCommand: npm cache clean --force && rm -rf .next node_modules && npm install && NODE_ENV=production npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: https://pdfmerger.onrender.com
      - key: NODE_VERSION
        value: 18.17.0
    autoDeploy: true
    plan: starter
    healthCheckPath: /api/healthcheck 