services:
  - type: web
    name: pdfmerger-api
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    autoDeploy: true
    healthCheckPath: /api/healthcheck
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    nodeVersion: 18.17.0 