services:
  - type: web
    name: pdfmerger-api
    env: node
    buildCommand: npm ci --only=production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: FRONTEND_URL
        value: "https://your-frontend-domain.vercel.app"
    autoDeploy: true
    healthCheckPath: /api/healthcheck
    scaling:
      minInstances: 1
      maxInstances: 5
      targetMemoryPercent: 70
      targetCPUPercent: 80
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 2
    nodeVersion: 18.17.0
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - server.js
        - api/**
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/* 